### ISSUE TITLE
I want Gomfile

### ISSUE THREAD

**Issue by uzimith** [ami-GS/simpleHTTP2#1]
I want to run this project. Would you mind creating Gomfile?

[mattn/gom](https://github.com/mattn/gom)
[rosylilly/gondler](https://github.com/rosylilly/gondler)

**Comment by ami-GS** [comment]
Looks fine!
Wait a moment please, I need to learn it.

**Comment by ami-GS** [comment]
I tried to write Gomfile, please test the code. Thanks!
